server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image: # 缩略图
#    width: 60
#    height: 60
#  tracker-list: # tracker地址
#    - 81.70.213.75:22122

mingrui:
  upload:
    path:
      windows: E:\\images
      linux: /yyq/images
    img:
      host: http://image.mrshop.com
